- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      update_cache: true
      state: present
    tags:
      - install
  tasks:
    - include: tasks/git.yml
      tags: git
