- hosts: localhost
  vars:
    admin_users:
      - sloveridge
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      update_cache: true
      state: present
    tags:
      - install
  tasks:
    - import_tasks: tasks/git.yml
      tags: git
    - import_tasks: tasks/tools.yml
      tags: tools
    - import_tasks: tasks/docker.yml
      tags: docker
