- name: docker gpg key
  become: true
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /tmp/docker.gpg
    mode: '0644'

- name: unpack gpg key
  become: true
  shell: cat /tmp/docker.gpg | gpg --dearmor -o /usr/share/keyrings/docker.gpg 

- name: docker repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: docker pacakages
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: add users to docker group
  become: true
  user: 
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ admin_users }}"
