- name: github gpg key
  become: true
  get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /usr/share/keyrings/githubcli-archive-keyring.gpg 
    mode: '0644'

- name: githug repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://cli.github.com/packages stable main"
    state: present
    update_cache: yes

- name: git pacakages
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - gh


- name: Git email
  git_config:
    name: user.email
    scope: global
    value: "sloveridge@gmail.com"

- name: Git name
  git_config:
    name: user.name
    scope: global
    value: "Shanon Loveridge"
